foldingathome/Dockerfile
foldingathome/build.json

Upgrades add-on base image to v4.2.3

⬆️ Upgrades add-on base image to v4.2.3

---

LICENSE.md
README.md
foldingathome/DOCS.md

📚 Update README & License

---

foldingathome/Dockerfile

⬆️ Upgrades FAH Client to 7.6.21

---

foldingathome/.README.j2
foldingathome/Dockerfile
foldingathome/config.json

A couple of small tweaks:
- Docker labels are more "automatic"
- Remove logger option, as it has no effect on the program itself
- Fix a maintenance label

🚜 Collection of tweaks

---

foldingathome/.README.j2

Broke when I renamed the main branch

📚 Fix screenshot in add-on readme template

---

foldingathome/Dockerfile
foldingathome/build.json

Upgrades the add-on base image to v5.0.0, which is based on Debian 11: Bullseye

⬆️ Upgrades add-on base image to v5.0.0

---

foldingathome/Dockerfile
foldingathome/build.yaml

pgrades add-on base image to 5.2.0

⬆️ Upgrades add-on base image to 5.2.0

---

foldingathome/Dockerfile
foldingathome/build.yaml

Upgrades add-on base image to 5.2.2

⬆️ Upgrades add-on base image to 5.2.2

---

LICENSE.md
README.md
foldingathome/.README.j2
foldingathome/DOCS.md

:fireworks: Updates maintenance/license year to 2022

---

foldingathome/Dockerfile
foldingathome/build.yaml

Upgrades add-on base image to 5.2.3

⬆️ Upgrades add-on base image to 5.2.3

---

foldingathome/Dockerfile
foldingathome/build.yaml

Upgrades add-on base image to 5.3.0

⬆️ Upgrades add-on base image to 5.3.0

---

.github/workflows/deploy.yaml
foldingathome/build.yaml
foldingathome/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

foldingathome/DOCS.md

Add My buttons to documentation

:books: Add My buttons to documentation

---

foldingathome/Dockerfile
foldingathome/build.yaml
foldingathome/rootfs/etc/services.d/fah/finish
foldingathome/rootfs/etc/services.d/fah/run

Upgrades add-on base image to 6.0.0

⬆️ Upgrades add-on base image to 6.0.0

---

foldingathome/DOCS.md

Making things just a tiny little bit easier

:books: Use new My Home Assistant link format

---

foldingathome/Dockerfile
foldingathome/build.yaml

⬆️ Upgrades add-on base image to 6.1.0

---

foldingathome/Dockerfile
foldingathome/build.yaml

⬆️ Upgrades add-on base image to 6.1.2

---

foldingathome/Dockerfile
foldingathome/build.yaml

⬆️ Upgrades add-on base image to 6.1.3

---

foldingathome/Dockerfile
foldingathome/build.yaml

⬆️ Upgrades add-on base image to 6.2.0

---

LICENSE.md
README.md
foldingathome/.README.j2
foldingathome/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

foldingathome/Dockerfile
foldingathome/build.yaml

⬆️ Upgrades add-on base image to 6.2.1

---

LICENSE.md
README.md
foldingathome/.README.j2
foldingathome/DOCS.md

:fireworks: Updates maintenance/license year to 2024
